[env]
GHQ_ROOT = "{{env.HOME}}/Documents/dev"

[tools]
1password = "latest"
claude = "latest"
gh = "latest"
ghq = "latest"
node = "latest"
starship = "latest"

"npm:difit" = "latest"
"npm:@openai/codex" = "latest"

"github:ushironoko/abbrs" = "latest"

[settings]
install_before = "7d"  # only install versions released more than 7 days ago
